# Generated by Django 2.2.4 on 2020-03-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200323_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinfo',
            name='pos',
            field=models.CharField(max_length=30, null=True, verbose_name='part of speech tag'),
        ),
        migrations.AlterUniqueTogether(
            name='wordinfo',
            unique_together=set(),
        ),
    ]
