# Generated by Django 3.0.3 on 2020-04-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200409_1800'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lexigrowuser',
            managers=[
            ],
        ),
    ]
