# Generated by Django 3.0.3 on 2020-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200409_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexigrowuser',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
