# Generated by Django 3.0.3 on 2020-04-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20200409_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinfo',
            name='level',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
