# Generated by Django 3.0.3 on 2020-04-10 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200410_1318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordinfo',
            unique_together={('word', 'pos')},
        ),
        migrations.CreateModel(
            name='SeenWordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.WordInfo')),
            ],
            options={
                'unique_together': {('word_info', 'user')},
            },
        ),
    ]
