# Generated by Django 3.0.3 on 2020-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20200410_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexigrowuser',
            name='show_harder_words',
            field=models.BooleanField(default=False, verbose_name='Show Harder Words'),
        ),
    ]
